<div class="portfolio">
    <h1>В данном разделе Вы можете посмотреть созданные плагины.</h1>
    <i>Большинство информационных продуктов разработанны под ключ и не могут быть представлены в данном разделе - по соглашению с заказчиком.</i>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-monstra"></span><span class="item-h1" title="Плагин для CMS Monstra">News</span></dt>
            <dd>
                <p>Плагин для публикации новостей.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/monstra/news" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-monstra"></span><span class="item-h1" title="Плагин для CMS Monstra">Catalog</span></dt>
            <dd>
                <p>Плагин для создания каталога.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/monstra/catalog" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Add Fields</span></dt>
            <dd>
                <p>Позволяет создавать дополнительные поля в профиле пользователя.
                <p>Поле может быть ссылкой или текстом.
                <p>Есть опция выноса текста поля под аватарку в сообщениях форума.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_fields" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">First post</span></dt>
            <dd>
                <p>Позволяет закрепить первое сообщение в темах форума
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_first_post" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Hide</span></dt>
            <dd>
                <p>Позволяет скрыть часть текста от гостей и пользователей не набравших определенное кол-во постов.
                <p>Админы и модераторы категорий видят скрытый текст.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/hide" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page1">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">jQuery UI</span></dt>
            <dd>
                <p>Позволяет подключить библиотеку jQuery UI.
                <p>Используется разработчиками для создания интерфейса пользователя.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_jquery_ui" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page2">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Topic Moderator</span></dt>
            <dd>
                <p>Позволяет определить группы в которых Автор темы получает права модератора.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_moder_author" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page2">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Move users</span></dt>
            <dd>
                <p>Автоматический перенос пользователей в группу при определенном кол-ве сообщений в темах форума.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_move_users_groups" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page2">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Smiles</span></dt>
            <dd>
                <p>Добавляет смайлы на форум.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_smiles" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page2">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Thanks</span></dt>
            <dd>
                <p>Позволяет сказать "Спасибо" пользователям за сообщение.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_thanks" target="_blank">Скачать</a>
        </div>
    </div>
    <div class="portfolio-item page2">
        <div class="desc">
            <dt><span class="icon-punbb"></span><span class="item-h1" title="Расширение для форума PunBB">Topic Description</span></dt>
            <dd>
                <p>Позволяет делать описание для тем.
                <p>Добавляет meta тег Description в темы форума.
            </dd>
        </div>
        <div class="download">
            <p><a href="http://files.kanekt.ru/punbb/nya_topic_desc" target="_blank">Скачать</a>
        </div>
    </div>
</div>
<div class="pagination">
    <ul>
        <li data-page="page1" class="active"><span>1</span></li>
        <li data-page="page2"><span>2</span></li>
    </ul>
</div>
